### ISSUE TITLE
[DEV] HomePage design and Implementation.

### ISSUE THREAD

**Issue by JiaHuann** [CnStarLab/CarRentalSys#1]
- Better to reorganize the front end directory.
- Make sure it can run properly before you push to master.
- Clearly write the commit with the same style.
- Better to add more comment on you code.

**Comment by Rensir56** [comment]
For the first task, I'd like to know the relationship between the car page and the carList page, and which page they come into

**Comment by JiaHuann** [comment]
> For the first task, I'd like to know the relationship between the car page and the carList page, and which page they come into

yeah，ok，you can see the car page is to create Car from user，car List is as a main component for guests to browse.
